name: Test dataset

on:
  pull_request:
    branches: main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Clone Hakai data repo test
        run: git clone https://HakaiInstitute:${{secrets.CI_TOKEN}}@github.com/HakaiInstitute/hakai-datasets-repo-standard-tests.git
      - name: Install Hakai Tests
        run: |
          python -m pip install --upgrade pip
          pip install pytest pandas
      - name: Test with pytest
        run: |
          pytest
      - name: Delete tests repo
        run: |
          git rm --cached hakai-datasets-repo-standard-tests
          rm -rf .gitmodules
          rm -rf hakai-datasets-repo-standard-tests
          rm -rf temp
          ls
