name: Synchronize Catalogue Record with dataset

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1 # Run every Monday at 00:00

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Sync metadata
        uses: hakaiinstitute/hakai-ckan-records-conversion/sync@main
        with:
            record-id: ca-cioos_66ad87d2-bb96-4515-a907-6367ca6c0a2b
            output-format: cff

