name: Synchornize Catalogue Record with dataset

on:
  workflow_dispatch:

steps:
  - name: Checkout code
    uses: actions/checkout@v4
  
  - name: Sync metadata
    uses: HakaiInstitute/hakai-ckan-records-conversion@main/sync
    with:
        dataset_id: ca-cioos_66ad87d2-bb96-4515-a907-6367ca6c0a2b
        outputs: contribution.cff
        format: cff
